spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manage?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: rootcdma
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 60000
      max-evictable-idle-time-millis: 90000
      validation-query: 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
      phy-max-use-count: 1000
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10
          connection-stack-trace-enable: true
      stat-view-servlet:
        enabled: true
        login-username: linilq
        login-password: rootcdma
        reset-enable: false
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: /*
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:/com/linilq/sys/mapping/*.xml
  type-aliases-package: com.linilq.sys.entity
